name: Compiles on Linux/MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os : [ubuntu-latest, macos-latest]
        build-config : ["debug", "release"]
        include:
          - os: ubuntu-latest
            build: make
          - os: macos-latest
            build: make

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ${{ matrix.build }} ${{ matrix.build-config }}
